# Generated by Django 3.2.8 on 2022-08-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='descripcion',
            new_name='description',
        ),
    ]
