# Generated by Django 3.2.8 on 2022-08-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_descripcion_lugar_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='description',
            new_name='descripcion',
        ),
    ]
