# Generated by Django 3.2.8 on 2022-09-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_description_lugar_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lugar',
            new_name='Mascotas',
        ),
    ]
