# Generated by Django 3.2.8 on 2022-10-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
