# Generated by Django 3.2.8 on 2022-10-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='titulo',
            field=models.TextField(max_length=100, verbose_name='Titulo'),
        ),
    ]
