# Generated by Django 3.2.8 on 2022-10-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_mascotas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(null=True, verbose_name='Precio'),
        ),
    ]
