# Generated by Django 3.2.8 on 2022-10-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20221019_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Precio'),
        ),
    ]
