# Generated by Django 3.2.8 on 2022-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_auto_20221020_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='precio',
            field=models.CharField(max_length=100, null=True, verbose_name='Precio'),
        ),
    ]
