# Generated by Django 3.2.8 on 2022-10-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_mascotas_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='precio',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='sexo',
            field=models.CharField(max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='telefono',
            field=models.IntegerField(max_length=9, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Precio'),
        ),
    ]
