# Generated by Django 3.2.8 on 2022-10-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_auto_20221022_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='telefono',
            field=models.CharField(max_length=9, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='titulo',
            field=models.CharField(max_length=40, verbose_name='Titulo'),
        ),
    ]
