# Generated by Django 3.2.8 on 2022-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_auto_20221022_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
