# Generated by Django 3.2.8 on 2022-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_alter_mascotas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
