# Generated by Django 3.2.8 on 2022-10-30 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_alter_mascotas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='fechaActual',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='titulo',
            field=models.CharField(help_text='Titulo de la mascota', max_length=40, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.CharField(max_length=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='titulo',
            field=models.CharField(help_text='Titulo del producto', max_length=100, verbose_name='Titulo'),
        ),
    ]
